const { test } = require("node:test");
const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

const root = join(__dirname, "..");

function read(relativePath) {
  return readFileSync(join(root, relativePath), "utf8");
}

function assertFileExists(relativePath) {
  assert.doesNotThrow(() => read(relativePath), `${relativePath} deve existir`);
}

test("landing envia pre-chamado publico para a API com JSON", () => {
  const script = read("apps/landing/script.js");

  assert.match(script, /http:\/\/localhost:3000\/api\/v1/);
  assert.match(script, /http:\/\/191\.252\.226\.11\/api\/v1/);
  assert.match(script, /`\$\{window\.location\.origin\}\/api\/v1`/);
  assert.match(script, /const apiBaseUrls = /);
  assert.match(script, /async function postPreChamado/);
  assert.match(script, /for \(const apiBaseUrl of apiBaseUrls\)/);
  assert.match(script, /fetch\(`\$\{apiBaseUrl\}\/site\/pre-chamados`/);
  assert.match(script, /method:\s*"POST"/);
  assert.match(script, /"Content-Type":\s*"application\/json"/);
  assert.match(script, /nome:\s*String\(data\.get\("nome"\)/);
  assert.match(script, /telefone:\s*String\(data\.get\("telefone"\)/);
  assert.match(script, /servico:\s*String\(data\.get\("servico"\)/);
  assert.match(script, /cep:\s*onlyDigits\(String\(data\.get\("cep"\)/);
  assert.match(script, /logradouro:\s*String\(data\.get\("logradouro"\)/);
  assert.match(script, /numero:\s*String\(data\.get\("numero"\)/);
  assert.match(script, /bairro:\s*String\(data\.get\("bairro"\)/);
  assert.match(script, /cidade:\s*String\(data\.get\("cidade"\)/);
  assert.match(script, /uf:\s*String\(data\.get\("uf"\)/);
  assert.doesNotMatch(script, /Enviar pelo WhatsApp/);
  assert.doesNotMatch(script, /buildWhatsAppMessage/);
});

test("landing mostra modal de sucesso com opcao imediata pelo WhatsApp", () => {
  const html = read("apps/landing/index.html");
  const script = read("apps/landing/script.js");
  const styles = read("apps/landing/css/style.css");

  assert.match(html, /id="bookingSuccessModal"/);
  assert.match(html, /\.\/js\/main\.js\?v=/);
  assert.match(html, /Em breve, um de nossos especialistas entrará em contato/);
  assert.match(html, /Se preferir um atendimento imediato/);
  assert.match(html, /id="bookingSuccessWhatsApp"/);
  assert.match(html, /data-booking-success-close/);
  assert.match(script, /function openBookingSuccessModal/);
  assert.match(script, /bookingSuccessModal\.classList\.add\("is-open"\)/);
  assert.match(script, /bookingSuccessWhatsApp\.href = buildWhatsAppUrl/);
  assert.match(styles, /\.booking-modal\.is-open/);
});

test("landing possui formulario de pre-chamado com CEP e limpeza de ar-condicionado", () => {
  const html = read("apps/landing/index.html");
  const script = read("apps/landing/script.js");

  assert.doesNotMatch(html, /Londriclima/i);
  assert.match(html, /AIRMOVEBR: climatiza/);
  assert.match(html, /novo padr/);
  assert.match(html, /Limpeza de ar-condicionado/);
  assert.match(html, /\.\/assets\/services\/pmoc-plataforma\.png/);
  assert.match(html, /\.\/assets\/services\/locacao-ar-condicionado\.png/);
  assert.doesNotMatch(html, /photo-1450101499163-c8848c66ca85/);
  assert.doesNotMatch(html, /photo-1521791136064-7986c2920216/);
  assert.match(html, /name="cep"/);
  assert.match(html, /name="logradouro"/);
  assert.match(html, /name="numero"/);
  assert.match(html, /name="complemento"/);
  assert.match(html, /name="bairro"/);
  assert.match(html, /name="cidade"/);
  assert.match(html, /name="uf"/);
  assert.match(html, /id="bookingCepStatus"/);
  assert.match(script, /https:\/\/viacep\.com\.br\/ws\/\$\{cep\}\/json\//);
  assert.match(script, /bookingCepStatus/);
  assert.match(script, /form\.elements\.logradouro\.value = address\.logradouro/);
  assert.match(script, /form\.elements\.bairro\.value = address\.bairro/);
  assert.match(script, /form\.elements\.cidade\.value = address\.localidade/);
  assert.match(script, /form\.elements\.uf\.value = address\.uf/);
});

test("admin autentica, guarda token e protege chamadas administrativas", () => {
  const script = read("apps/admin/script.js");
  const html = read("apps/admin/index.html");
  const main = read("apps/admin/js/main.js");

  assert.match(html, /<script type="module" src="\.\/js\/main\.js"><\/script>/);
  assert.match(main, /import "\.\.\/script\.js"/);
  assert.match(main, /adminModules/);
  assertFileExists("apps/admin/js/modules/agenda.js");
  assertFileExists("apps/admin/js/modules/recorrencias.js");
  assertFileExists("apps/admin/js/modules/frota.js");
  assertFileExists("apps/admin/js/modules/clientes.js");
  assertFileExists("apps/admin/js/modules/pmoc.js");

  assert.match(script, /http:\/\/localhost:3000\/api\/v1/);
  assert.match(script, /https:\/\/api\.airmovebr\.com\.br\/api\/v1/);
  assert.match(script, /\/auth\/login/);
  assert.match(script, /localStorage\.setItem\("airmovebr_access_token"/);
  assert.match(script, /Authorization:\s*`Bearer \$\{getToken\(\)\}`/);
  assert.match(script, /\/admin\/pre-chamados/);
  assert.match(script, /\/admin\/frota\/localizacoes/);
  assert.match(script, /\/admin\/agenda/);
  assert.match(script, /\/admin\/planos-recorrencia/);
  assert.match(script, /\/admin\/empresa/);
  assert.match(script, /\/admin\/clientes/);
  assert.match(script, /\/admin\/relatorios/);
  assert.match(script, /\/admin\/relatorios-avulsos/);
  assert.match(script, /\/admin\/frota\/abastecimentos/);
  assert.match(script, /\/admin\/relatorios\/frota/);
  assert.match(script, /\/admin\/engenheiros\/\$\{engineerId\}/);
  assert.match(script, /response\.status !== 401/);
});

test("admin possui views funcionais para agenda clientes e relatorios", () => {
  const html = read("apps/admin/index.html");
  const script = read("apps/admin/script.js");
  const agendaModule = read("apps/admin/js/modules/agenda.js");
  const recorrenciasModule = read("apps/admin/js/modules/recorrencias.js");
  const clientesModule = read("apps/admin/js/modules/clientes.js");

  assert.match(html, /data-view="agenda"/);
  assert.match(html, /data-view="recorrencias"/);
  assert.match(html, /data-view="empresa"/);
  assert.match(html, /data-view="clientes"/);
  assert.match(html, /data-view="relatorios"/);
  assert.match(html, /data-view="relatoriosAvulsos"/);
  assert.match(html, /id="agendaView"/);
  assert.match(html, /id="newAgendaOsButton"/);
  assert.match(html, /id="agendaCalendar"/);
  assert.match(html, /id="agendaPendingList"/);
  assert.match(html, /id="agendaSelectedDateTitle"/);
  assert.match(html, /id="agendaList"/);
  assert.match(html, /id="agendaOsModal"/);
  assert.match(html, /id="agendaOsForm"/);
  assert.match(html, /name="cliente_id"/);
  assert.match(html, /name="agendada_para"/);
  assert.match(html, /name="tecnico_id"/);
  assert.match(html, /id="recorrenciasView"/);
  assert.match(html, /id="recurrenceForm"/);
  assert.match(html, /id="recurrenceList"/);
  assert.match(html, /name="frequencia"/);
  assert.match(html, /name="proxima_execucao"/);
  assert.match(html, /id="clientesView"/);
  assert.match(html, /id="empresaView"/);
  assert.match(html, /id="empresaForm"/);
  assert.match(html, /name="razao_social"/);
  assert.match(html, /name="nome_fantasia"/);
  assert.match(html, /name="inscricao_estadual"/);
  assert.match(html, /name="responsavel_legal"/);
  assert.match(html, /name="telefone"[^>]+required/);
  assert.match(html, /id="clientDocumentLabel"/);
  assert.match(html, /id="deleteClientModal"/);
  assert.match(html, /id="confirmDeleteClientButton"/);
  assert.match(html, /id="clientEquipmentPanel"/);
  assert.match(html, /id="equipmentForm"/);
  assert.match(html, /name="codigo_barras"/);
  assert.match(html, /Codigo de barras ou QR Code/);
  assert.match(html, /Ler codigo\/QR/);
  assert.match(html, /name="gas_refrigerante"/);
  assert.match(html, /R-410A/);
  assert.match(html, /id="scanEquipmentCodeButton"/);
  assert.match(html, /name="cep"/);
  assert.match(html, /id="clientCepStatus"/);
  assert.doesNotMatch(html, /assinatura_digitalizada|Assinatura digitalizada/);
  assert.match(html, /id="relatoriosView"/);
  assert.match(html, /id="printReportsButton"/);
  assert.match(html, /id="relatoriosAvulsosView"/);
  assert.match(html, /id="relatoriosAvulsosList"/);
  assert.match(script, /async function loadAgenda/);
  assert.match(agendaModule, /view:\s*"agenda"/);
  assert.match(agendaModule, /summaryId:\s*"agendaSummary"/);
  assert.match(script, /async function submitAgendaOs/);
  assert.match(script, /function openAgendaOsModal/);
  assert.match(script, /function renderAgendaMonthGrid/);
  assert.match(script, /function renderAgendaCalendar/);
  assert.match(script, /function renderAgendaDay/);
  assert.match(script, /function renderAgendaPendingList/);
  assert.match(script, /function getAgendaStatusClass/);
  assert.match(script, /function buildAgendaSlots/);
  assert.match(script, /\/admin\/agenda\/ordens/);
  assert.match(script, /\/admin\/agenda\/ordens\/\$\{agendaEditingOsId\}/);
  assert.match(script, /async function loadRecorrencias/);
  assert.match(recorrenciasModule, /view:\s*"recorrencias"/);
  assert.match(script, /async function submitRecurrence/);
  assert.match(script, /function renderRecorrencias/);
  assert.match(script, /function renderRecurrenceCard/);
  assert.match(script, /function generateRecurrenceOs/);
  assert.match(script, /\/admin\/planos-recorrencia\/\$\{planId\}\/gerar-os/);
  assert.match(script, /const AGENDA_LOOKAHEAD_DAYS = 180/);
  assert.match(script, /offset <= AGENDA_LOOKAHEAD_DAYS/);
  assert.match(script, /selectedAgendaDate = button\.dataset\.agendaDate/);
  assert.match(script, /async function loadEmpresa/);
  assert.match(script, /async function submitEmpresa/);
  assert.match(script, /fetch\(`\$\{apiBaseUrl\}\/admin\/empresa`/);
  assert.match(script, /async function loadClientes/);
  assert.match(clientesModule, /view:\s*"clientes"/);
  assert.match(script, /async function loadRelatorios/);
  assert.match(script, /function renderPeriodMetric/);
  assert.match(script, /function openReportsPrint/);
  assert.match(script, /printReportsButton\?\.addEventListener\("click", openReportsPrint\)/);
  assert.match(script, /Receita arrecadada/);
  assert.match(script, /async function loadRelatoriosAvulsos/);
  assert.match(script, /openRelatorioAvulsoPdf/);
  assert.match(script, /enviarRelatorioAvulso/);
  assert.match(script, /\/admin\/relatorios-avulsos\/clientes\/\$\{clientId\}\/pdf/);
  assert.match(script, /\/admin\/relatorios-avulsos\/clientes\/\$\{clientId\}\/enviar/);
  assert.match(script, /https:\/\/viacep\.com\.br\/ws\/\$\{cep\}\/json\//);
  assert.match(script, /cep:\s*onlyDigits\(String\(data\.get\("cep"\)/);
  assert.match(script, /clientForm\.elements\.logradouro\.value = address\.logradouro/);
  assert.match(script, /clientForm\.elements\.cidade\.value = address\.localidade/);
  assert.match(script, /clientForm\.elements\.uf\.value = address\.uf/);
  assert.match(script, /function validateClientIdentity/);
  assert.match(script, /Telefone com DDD|Informe telefone com DDD/);
  assert.match(script, /tipo === "pj" \? "CNPJ" : "CPF ou RG"/);
  assert.match(script, /data-action="apagar-cliente"/);
  assert.match(script, /data-action="apagar-engenheiro"/);
  assert.match(script, /async function deleteEngineer/);
  assert.match(script, /method:\s*"DELETE"/);
  assert.match(script, /\/admin\/clientes\/\$\{selectedEquipmentClientId\}\/equipamentos/);
  assert.match(script, /gas_refrigerante:\s*String\(data\.get\("gas_refrigerante"\)/);
  assert.match(script, /Gas: \$\{escapeHtml\(item\.gas_refrigerante/);
  assert.match(script, /\/admin\/equipamentos\/\$\{equipmentId\}\/renovar-acesso/);
  assert.match(script, /\/admin\/equipamentos\/\$\{equipmentId\}/);
  assert.match(script, /BarcodeDetector/);
  assert.match(script, /qr_code/);
  assert.match(script, /data-action="renovar-acesso-equipamento"/);
  assert.match(script, /data-action="apagar-equipamento"/);
  assert.match(html, /id="backToClientsButton"/);
  assert.match(script, /backToClientsButton\?\.classList\.remove\("hidden"\)/);
  assert.match(script, /backToClientsButton\?\.classList\.add\("hidden"\)/);
  assert.match(script, /backToClientsButton\?\.addEventListener\("click", resetClientForm\)/);
  assert.match(script, /clientesList\.classList\.add\("hidden"\)/);
  assert.match(script, /clientesList\.classList\.remove\("hidden"\)/);
});

test("admin gerencia tecnicos equipes e responsaveis flexiveis por OS", () => {
  const html = read("apps/admin/index.html");
  const script = read("apps/admin/script.js");

  assert.match(html, /data-view="tecnicos"/);
  assert.match(html, /data-view="equipes"/);
  assert.match(html, /id="tecnicosView"/);
  assert.match(html, /id="tecnicoForm"/);
  assert.match(html, /name="senha"/);
  assert.match(html, /id="equipesView"/);
  assert.match(html, /id="equipeForm"/);
  assert.match(html, /id="equipeMembersList"/);
  assert.match(html, /name="equipe_ids"[^>]*multiple/);
  assert.match(script, /async function loadTecnicos/);
  assert.match(script, /\/admin\/tecnicos/);
  assert.match(script, /async function loadEquipes/);
  assert.match(script, /\/admin\/equipes/);
  assert.match(script, /function renderEquipeMembersList/);
  assert.match(script, /usuario_ids:\s*data\.getAll\("usuario_ids"\)/);
  assert.match(script, /equipe_ids:\s*data\.getAll\("equipe_ids"\)/);
});

test("landing possui consulta publica de equipamento protegida por senha", () => {
  const html = read("apps/landing/equipamento.html");
  const script = read("apps/landing/equipamento.js");

  assert.match(html, /id="equipmentAccessForm"/);
  assert.match(html, /name="senha"/);
  assert.match(html, /id="equipmentResultPanel"/);
  assert.match(script, /\/site\/equipamentos\/\$\{encodeURIComponent\(codigo\)\}\/acessar/);
  assert.match(script, /method:\s*"POST"/);
  assert.match(script, /senha/);
  assert.doesNotMatch(script, /telefone|documento|valor/);
});

test("landing possui assinatura publica de PMOC por token", () => {
  const html = read("apps/landing/assinatura-pmoc.html");
  const script = read("apps/landing/assinatura-pmoc.js");

  assert.match(html, /id="pmocSignaturePanel"/);
  assert.match(html, /id="pmocSignatureStatus"/);
  assert.match(html, /id="pmocSignedPdfInput"/);
  assert.match(html, /type="file"/);
  assert.match(html, /accept="application\/pdf"/);
  assert.match(html, /id="pmocSignatureConfirmButton"/);
  assert.match(script, /URLSearchParams\(window\.location\.search\)/);
  assert.match(script, /\/site\/pmoc\/assinaturas\/\$\{encodeURIComponent\(token\)\}/);
  assert.match(script, /\/site\/pmoc\/assinaturas\/\$\{encodeURIComponent\(token\)\}\/confirmar/);
  assert.match(script, /method:\s*"POST"/);
  assert.match(script, /pdf_assinado_base64/);
  assert.match(script, /FileReader/);
  assert.match(script, /pdf_hash/);
});

test("admin possui triagem PMOC por cliente e conversao com engenheiro", () => {
  const html = read("apps/admin/index.html");
  const script = read("apps/admin/script.js");
  const styles = read("apps/admin/styles.css");
  const pmocModule = read("apps/admin/js/modules/pmoc.js");

  assert.match(html, /data-view="pmoc"/);
  assert.match(html, /id="pmocView"/);
  assert.match(html, /id="pmocSearchForm"/);
  assert.match(html, /id="pmocSearchInput"/);
  assert.match(html, /id="pmocHero"/);
  assert.match(html, /id="pmocSearchPanel"/);
  assert.match(html, /class="pmoc-grid hidden" id="pmocSearchPanel"/);
  assert.match(html, /id="pmocSearchResults"/);
  assert.match(html, /id="pmocConversionPanel"/);
  assert.match(html, /id="pmocEngineerSelect"/);
  assert.match(html, /id="pmocDossierPanel"/);
  assert.match(html, /id="pmocDossierList"/);
  assert.match(html, /id="pmocDossierDetail"/);
  assert.match(html, /id="pmocMonthBoard"/);
  assert.match(html, /id="pmocBackToClientsButton"/);
  assert.match(html, /Voltar para clientes/);
  assert.match(html, /id="pmocMachineList"/);
  assert.match(html, /id="pmocGenerateReportButton"[^>]*disabled/);
  assert.match(html, /id="pmocRequestSignatureButton"[^>]*disabled/);
  assert.match(script, /function loadPmoc/);
  assert.match(pmocModule, /view:\s*"pmoc"/);
  assert.match(pmocModule, /summaryId:\s*"pmocSummary"/);
  assert.match(script, /function searchPmocClients/);
  assert.match(script, /function resetPmocSearchResults/);
  assert.match(script, /function openPmocConversion/);
  assert.match(script, /function activatePmocClient/);
  assert.match(script, /function setPmocDossierMode/);
  assert.match(script, /function openPmocDossier/);
  assert.match(script, /function closePmocDossier/);
  assert.match(script, /function renderPmocMachines/);
  assert.match(script, /function renderPmocMonths/);
  assert.match(script, /pmoc_meses/);
  assert.match(script, /is-sent/);
  assert.match(script, /is-pending/);
  assert.match(script, /function openPmocReportPreview/);
  assert.match(script, /hasCompletedPmocMaintenance/);
  assert.match(script, /function getCurrentPmocMonth/);
  assert.match(script, /hasDeliveredCurrentMonth/);
  assert.match(script, /email_entregue/);
  assert.match(script, /function isPmocTestClient/);
  assert.match(script, /cris magnani/);
  assert.match(script, /isPmocTestClient\(client\)/);
  assert.match(script, /PMOC enviado/);
  assert.match(script, /pmocGenerateReportButton\?\.addEventListener\("click", openPmocReportPreview\)/);
  assert.match(script, /pmocBackToClientsButton\?\.addEventListener\("click", closePmocDossier\)/);
  assert.match(script, /pmocDossierPanel\?\.classList\.toggle\("hidden", isOpen\)/);
  assert.match(script, /pmocHero\?\.classList\.toggle\("hidden", isOpen\)/);
  assert.match(script, /\/admin\/clientes\/\$\{client\.id\}\/equipamentos/);
  assert.match(script, /\/admin\/pmoc\/clientes\/\$\{selectedPmocDossierClientId\}\/previa/);
  assert.match(script, /\/admin\/pmoc\/clientes\/\$\{selectedPmocDossierClientId\}\/pdf/);
  assert.match(script, /\/assinaturas\/pmoc\/clientes\/\$\{selectedPmocDossierClientId\}\/assinafy/);
  assert.match(script, /assinafy_document_id/);
  assert.match(script, /canRequestSignature/);
  assert.doesNotMatch(script, /token_assinatura/);
  assert.match(script, /pronto_para_pdf/);
  assert.match(script, /total_os_concluidas/);
  assert.match(script, /os_concluidas/);
  assert.match(script, /pmoc_ativo:\s*true/);
  assert.match(script, /engenheiro_responsavel_id:\s*engineerId/);
  assert.match(styles, /\.pmoc-hero/);
  assert.match(styles, /\.pmoc-client-card/);
  assert.match(styles, /\.pmoc-dossier-row/);
  assert.match(styles, /\.pmoc-dossier-detail/);
  assert.match(styles, /\.pmoc-workspace\.is-dossier-open/);
  assert.match(styles, /\.pmoc-month-grid/);
  assert.match(styles, /\.pmoc-month-card\.is-sent/);
  assert.match(styles, /\.pmoc-month-card\.is-pending/);
  assert.match(styles, /\.pmoc-month-card\.is-waiting-signature/);
  assert.match(script, /getPmocMonthStatus/);
  assert.match(script, /Aguardando assinatura/);
  assert.match(script, /Enviado ao cliente/);
  assert.match(styles, /\.pmoc-machine-card/);
  assert.doesNotMatch(html, /id="pmocEquipmentFields"/);
  assert.doesNotMatch(html, /id="pmocChecklist"/);
  assert.doesNotMatch(html, /id="pmocAirQuality"/);
  assert.doesNotMatch(html, /id="pmocDocuments"/);
  assert.doesNotMatch(html, /id="pmocHospital"/);
  assert.doesNotMatch(script, /const pmocEquipmentRegistry/);
  assert.doesNotMatch(script, /function renderPmocGroup/);
  assert.doesNotMatch(styles, /\.pmoc-board/);
  assert.doesNotMatch(styles, /\.pmoc-check/);
});

test("admin separa frota em mapa consumo e abastecimentos", () => {
  const html = read("apps/admin/index.html");
  const script = read("apps/admin/script.js");
  const frotaModule = read("apps/admin/js/modules/frota.js");

  assert.match(html, /data-fleet-tab="mapa"/);
  assert.match(html, /data-fleet-tab="consumo"/);
  assert.match(html, /data-fleet-tab="abastecimentos"/);
  assert.match(html, /id="fleetReportExportButton"/);
  assert.match(html, /id="fleetReportList"/);
  assert.match(html, /id="fuelHistoryList"/);
  assert.match(html, /id="fuelForm"/);
  assert.match(html, /Registrar abastecimento manual/);
  assert.match(script, /function setFleetTab/);
  assert.match(frotaModule, /view:\s*"frota"/);
  assert.match(script, /async function loadRelatorioFrota/);
  assert.match(script, /async function submitFuel/);
  assert.match(script, /function openFleetReport/);
});

test("admin mostra todos os veiculos no Leaflet e permite zoom por carro", () => {
  const html = read("apps/admin/index.html");
  const script = read("apps/admin/script.js");
  const styles = read("apps/admin/styles.css");

  assert.match(html, /\.\/vendor\/leaflet\/leaflet\.css/);
  assert.match(html, /\.\/vendor\/leaflet\/leaflet\.js/);
  assert.match(styles, /@import "\.\/css\/base\.css"/);
  assert.match(styles, /@import "\.\/css\/layout\.css"/);
  assert.match(styles, /@import "\.\/css\/agenda\.css"/);
  assert.match(styles, /@import "\.\/css\/frota\.css"/);
  assert.match(styles, /@import "\.\/css\/clientes\.css"/);
  assert.match(styles, /@import "\.\/css\/pmoc\.css"/);
  assertFileExists("apps/admin/css/base.css");
  assertFileExists("apps/admin/css/layout.css");
  assertFileExists("apps/admin/css/agenda.css");
  assertFileExists("apps/admin/css/frota.css");
  assertFileExists("apps/admin/css/clientes.css");
  assertFileExists("apps/admin/css/pmoc.css");
  assert.doesNotMatch(html, /openstreetmap\.org\/export\/embed\.html/);
  assert.match(script, /L\.map\(fleetMap/);
  assert.match(script, /L\.tileLayer\("https:\/\/\{s\}\.tile\.openstreetmap\.org/);
  assert.match(script, /L\.marker\(\[latitude, longitude\]/);
  assert.match(script, /leafletMap\.fitBounds\(fleetMarkerGroup\.getBounds\(\)/);
  assert.match(script, /function focusVehicleOnMap/);
  assert.match(script, /leafletMap\.setView\(marker\.getLatLng\(\), 17/);
  assert.match(script, /selectFleetVehicle\(card\.dataset\.vehicleId\)/);
  assert.match(styles, /\.leaflet-container/);
  assert.doesNotMatch(html, /map-road|Av\. Higienópolis|Av\. Dez de Dezembro|BR-369/);
  assert.doesNotMatch(styles, /\.map-road|\.vehicle-marker/);
});
