export const comercialModule = { view: "comercial", viewId: "comercialView" };

export const comercialRoot = `
const comercialCss = document.createElement("link");
comercialCss.rel = "stylesheet"; comercialCss.href = "./css/comercial.css?v=20260723-comercial"; document.head.append(comercialCss);
const comercialNav = document.createElement("button");
comercialNav.className = "nav-link"; comercialNav.type = "button"; comercialNav.dataset.view = "comercial"; comercialNav.textContent = "Catálogo e orçamentos";
document.querySelectorAll(".nav-group")[1]?.append(comercialNav);
const comercialView = document.createElement("section");
comercialView.className = "worklist hidden comercial-workspace"; comercialView.id = "comercialView";
comercialView.innerHTML = \`<div class="comercial-header"><div><span class="kicker">Comercial</span><h2>Catálogo e orçamentos</h2><p>Cadastre itens e acompanhe as propostas enviadas aos clientes.</p></div><button class="refresh-button compact-button" id="comercialRefreshButton" type="button">Atualizar</button></div><div class="comercial-grid"><section class="comercial-panel"><div class="comercial-panel-title"><div><span>CATÁLOGO</span><h3>Novo item</h3></div><p>Serviços, materiais, peças e equipamentos.</p></div><form id="comercialCatalogForm" class="comercial-form"><label>Tipo<select name="tipo"><option value="servico">Serviço</option><option value="material">Material</option><option value="peca">Peça</option><option value="equipamento">Equipamento</option></select></label><label>Grupo<input name="grupo" placeholder="Ex.: Climatização" required></label><label>Subgrupo<input name="subgrupo" placeholder="Ex.: Instalação"></label><label>Nome<input name="nome" placeholder="Ex.: Instalação split 12.000 BTU" required></label><label>Código<input name="codigo" placeholder="Opcional"></label><label>Unidade<input name="unidade" value="un" required></label><label>Custo<input name="custo" type="number" min="0" step="0.01" value="0" required></label><label>Preço de venda<input name="valor" type="number" min="0" step="0.01" required></label><label class="comercial-field-wide">Descrição<textarea name="descricao" rows="2" placeholder="Opcional"></textarea></label><button type="submit">Salvar item</button></form></section><section class="comercial-panel comercial-catalog-list"><div class="comercial-panel-title"><div><span>ITENS ATIVOS</span><h3>Catálogo</h3></div><strong id="comercialCatalogCount">0</strong></div><div id="comercialCatalogItems"></div></section></div><section class="comercial-panel comercial-quotes"><div class="comercial-panel-title"><div><span>PROPOSTAS</span><h3>Orçamentos recentes</h3></div></div><div id="comercialQuoteItems"></div></section>\`;
document.querySelector("#dashboard")?.append(comercialView);
let comercialCatalog = [];
function comercialMoney(value) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0)); }
function comercialEscape(value) { const node = document.createElement("div"); node.textContent = String(value ?? ""); return node.innerHTML; }
function comercialDate(value) { return value ? new Date(value).toLocaleDateString("pt-BR") : "Sem validade"; }
function renderComercialCatalog() { const target = document.querySelector("#comercialCatalogItems"); document.querySelector("#comercialCatalogCount").textContent = comercialCatalog.length; target.innerHTML = comercialCatalog.length ? comercialCatalog.map((item) => \`<article class="catalog-item"><div><span>\${comercialEscape(item.tipo)} · \${comercialEscape(item.grupo)}\${item.subgrupo ? \` / \${comercialEscape(item.subgrupo)}\` : ""}</span><strong>\${comercialEscape(item.nome)}</strong><small>\${comercialEscape(item.unidade)}\${item.codigo ? \` · \${comercialEscape(item.codigo)}\` : ""}</small></div><b>\${comercialMoney(item.valor)}</b></article>\`).join("") : '<p class="comercial-empty">Nenhum item cadastrado.</p>'; }
function renderComercialQuotes(items) { const target = document.querySelector("#comercialQuoteItems"); target.innerHTML = items.length ? items.map((quote) => \`<article class="quote-item"><div><span>\${comercialEscape(quote.status)}</span><strong>\${comercialEscape(quote.titulo)}</strong><small>\${comercialEscape(quote.cliente.nome)} · \${quote._count.itens} item(ns) · \${comercialDate(quote.validoAte)}</small></div><b>\${comercialMoney(quote.total)}</b></article>\`).join("") : '<p class="comercial-empty">Nenhum orçamento criado.</p>'; }
async function loadCommercial() { const [catalogResponse, quoteResponse] = await Promise.all([fetch(\`\${apiBaseUrl}/admin/comercial/catalogo\`, { headers: authHeaders() }), fetch(\`\${apiBaseUrl}/admin/comercial/orcamentos\`, { headers: authHeaders() })]); if (catalogResponse.ok) { comercialCatalog = (await catalogResponse.json()).items || []; renderComercialCatalog(); } if (quoteResponse.ok) renderComercialQuotes((await quoteResponse.json()).items || []); }
function hideCommercialView() { comercialView.classList.add("hidden"); }
function showCommercialView() { document.querySelectorAll("[id$='View'], [id$='Summary']").forEach((element) => element.classList.add("hidden")); document.querySelectorAll(".nav-link").forEach((element) => element.classList.toggle("active", element === comercialNav)); viewKicker.textContent = "Comercial"; viewTitle.textContent = "Catálogo e orçamentos"; comercialView.classList.remove("hidden"); hideWhatsappView(); void loadCommercial(); }
comercialNav.addEventListener("click", (event) => { event.stopImmediatePropagation(); showCommercialView(); });
document.querySelectorAll(".nav-link").forEach((link) => link.addEventListener("click", () => { if (link !== comercialNav) hideCommercialView(); }));
document.querySelector("#comercialRefreshButton").addEventListener("click", () => void loadCommercial());
document.querySelector("#comercialCatalogForm").addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.target); const response = await fetch(\`\${apiBaseUrl}/admin/comercial/catalogo\`, { method: "POST", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) }); if (!response.ok) { const error = await response.json().catch(() => null); window.alert(error?.message || "Não foi possível salvar o item."); return; } event.target.reset(); event.target.elements.unidade.value = "un"; event.target.elements.custo.value = "0"; await loadCommercial(); });
`;
