export const whatsappModule = { view: "whatsapp", summaryId: "whatsappSummary", viewId: "whatsappView" };

export const whatsappRoot = `
const whatsappNav = document.createElement("button");
whatsappNav.className = "nav-link";
whatsappNav.type = "button";
whatsappNav.dataset.view = "whatsapp";
whatsappNav.textContent = "Conversas WhatsApp";
document.querySelector(".nav-group")?.append(whatsappNav);

const whatsappSummary = document.createElement("section");
whatsappSummary.className = "summary-grid hidden whatsapp-summary";
whatsappSummary.id = "whatsappSummary";
document.querySelector("#dashboard")?.insertBefore(whatsappSummary, document.querySelector("#preChamadosSummary"));

const whatsappView = document.createElement("section");
whatsappView.className = "worklist hidden whatsapp-workspace";
whatsappView.id = "whatsappView";
whatsappView.innerHTML = \`
  <div class="whatsapp-page-header"><span class="kicker">Central de atendimento</span></div>
  <div class="whatsapp-inbox" role="region" aria-label="Central de conversas WhatsApp">
    <aside class="whatsapp-inbox-list">
      <div class="whatsapp-list-head"><div><strong>Caixa de entrada</strong><span class="whatsapp-list-count" id="whatsappListStatus">Carregando...</span></div><button class="whatsapp-icon-button" id="whatsappRefreshButton" type="button" aria-label="Atualizar conversas" title="Atualizar conversas">Atualizar</button></div>
      <label class="whatsapp-search"><span class="sr-only">Pesquisar conversa</span><input id="whatsappSearchInput" type="search" placeholder="Pesquisar nome ou telefone" autocomplete="off" /></label>
      <div class="whatsapp-filters" role="tablist" aria-label="Filtro de conversas"><button class="is-active" type="button" data-whatsapp-filter="todas">Todas</button><button type="button" data-whatsapp-filter="aguardando">Aguardando <span id="whatsappPendingBadge">0</span></button><button type="button" data-whatsapp-filter="atendimento">Em atendimento</button><button type="button" data-whatsapp-filter="encerradas">Encerradas</button></div>
      <div class="whatsapp-conversation-list" id="whatsappConversationList"></div>
    </aside>
    <section class="whatsapp-conversation-detail" id="whatsappConversationDetail"><div class="whatsapp-empty-state"><span class="whatsapp-empty-icon">◉</span><strong>Selecione uma conversa</strong><p>As mensagens, o cadastro e o agendamento aparecerão aqui.</p></div></section>
  </div>\`;
document.querySelector("#dashboard")?.append(whatsappView);

let whatsappConversations = [];
let selectedWhatsappId = "";
let selectedWhatsappConversation = null;
let whatsappRefreshTimer = 0;
let whatsappEventAbort = null;
let lastWhatsappEvent = "";
let whatsappScheduleOptions = { equipes: [], tecnicos: [], agenda: [] };
let whatsappCatalogItems = [];
let whatsappSelectedScheduleDate = "";
let whatsappScheduleDraft = { equipeId: "", tecnicoId: "" };
const whatsappTopbar = document.querySelector(".topbar");

function esc(value) { const div = document.createElement("div"); div.textContent = String(value ?? ""); return div.innerHTML; }
function formatDate(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? String(value || "") : date.toLocaleString("pt-BR"); }
function localDate(value = new Date()) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 10); }
function hideWhatsappView() { whatsappView.classList.add("hidden"); whatsappSummary.classList.add("hidden"); whatsappTopbar?.classList.remove("hidden"); refreshButton?.classList.remove("hidden"); window.clearInterval(whatsappRefreshTimer); whatsappEventAbort?.abort(); }
function showWhatsappView() { document.querySelectorAll("[id$='View'], [id$='Summary']").forEach((e) => e.classList.add("hidden")); document.querySelectorAll(".nav-link").forEach((e) => e.classList.toggle("active", e === whatsappNav)); viewKicker.textContent = "Atendimento digital"; viewTitle.textContent = "Conversas WhatsApp"; whatsappTopbar?.classList.add("hidden"); refreshButton?.classList.add("hidden"); whatsappView.classList.remove("hidden"); window.clearInterval(whatsappRefreshTimer); void loadWhatsappConversations(); whatsappRefreshTimer = window.setInterval(() => void loadWhatsappConversations(), 60000); void connectWhatsappEvents(); }

async function loadWhatsappConversations() {
  const status = document.querySelector("#whatsappListStatus");
  const response = await fetch(\`\${apiBaseUrl}/admin/whatsapp/conversas\`, { headers: authHeaders() });
  if (await handleUnauthorized(response)) return;
  if (!response.ok) { status.textContent = "Não foi possível carregar."; return; }
  const result = await response.json(); whatsappConversations = result.items || [];
  const pendingCount = result.pendentes ?? whatsappConversations.filter((item) => item.status === "humano" && !item.atribuidoUsuarioId).length;
  document.querySelector("#whatsappPendingBadge").textContent = pendingCount;
  status.textContent = whatsappConversations.length ? \`\${whatsappConversations.length} conversas\` : "Nenhuma conversa";
  renderWhatsappConversations();
}

function getWhatsappState(item) {
  if (item.status === "encerrada") return { key: "encerradas", className: "is-closed", label: "Encerrada", ageMinutes: 0 };
  if (item.status === "humano" && item.atribuidoUsuarioId) return { key: "atendimento", className: "is-attending", label: "Em atendimento", ageMinutes: 0 };
  const reference = new Date(item.ultimaMensagemEm || item.criadoEm || Date.now());
  const ageMinutes = Number.isNaN(reference.getTime()) ? 0 : Math.max(0, Math.floor((Date.now() - reference.getTime()) / 60000));
  return ageMinutes >= 15 ? { key: "aguardando", className: "is-overdue", label: "Aguardando há muito tempo", ageMinutes } : { key: "aguardando", className: "is-waiting", label: "Aguardando atendimento", ageMinutes };
}
function formatWaiting(ageMinutes) { return ageMinutes < 1 ? "Agora" : ageMinutes < 60 ? \`\${ageMinutes} min\` : \`\${Math.floor(ageMinutes / 60)} h \${ageMinutes % 60} min\`; }
function renderWhatsappConversations() {
  const list = document.querySelector("#whatsappConversationList"); const query = String(document.querySelector("#whatsappSearchInput")?.value || "").toLowerCase().trim(); const filter = document.querySelector("[data-whatsapp-filter].is-active")?.dataset.whatsappFilter || "todas";
  const items = whatsappConversations.filter((item) => { const state = getWhatsappState(item); const text = \`\${item.nomeContato || ""} \${item.telefone || ""}\`.toLowerCase(); return (!query || text.includes(query)) && (filter === "todas" || filter === state.key); });
  list.innerHTML = items.length ? items.map((item) => { const state = getWhatsappState(item); const last = item.mensagens?.[0]?.texto || "Sem mensagens"; return \`<button class="whatsapp-conversation-card \${state.className} \${selectedWhatsappId === item.id ? "is-selected" : ""}" type="button" data-whatsapp-id="\${esc(item.id)}"><span class="whatsapp-status-dot" aria-hidden="true"></span><span class="whatsapp-avatar">\${esc((item.nomeContato || item.telefone || "?").slice(0, 1).toUpperCase())}</span><span class="whatsapp-conversation-copy"><strong>\${esc(item.nomeContato || item.telefone)}</strong><small>\${esc(last.slice(0, 78))}</small><em>\${state.label}</em></span><span class="whatsapp-conversation-time">\${state.ageMinutes ? formatWaiting(state.ageMinutes) : ""}</span></button>\`; }).join("") : '<div class="whatsapp-list-empty">Nenhuma conversa encontrada.</div>';
}

async function loadWhatsappScheduleOptions() {
  if (whatsappScheduleOptions.equipes.length || whatsappScheduleOptions.tecnicos.length) {
    const response = await fetch(\`\${apiBaseUrl}/admin/agenda\`, { headers: authHeaders() });
    whatsappScheduleOptions.agenda = response.ok ? (await response.json()).items || [] : [];
    return;
  }
  const [equipes, tecnicos, agenda] = await Promise.all(["equipes", "tecnicos", "agenda"].map((route) => fetch(\`\${apiBaseUrl}/admin/\${route}\`, { headers: authHeaders() }).then((response) => response.ok ? response.json() : { items: [] }).catch(() => ({ items: [] }))));
  whatsappScheduleOptions = { equipes: equipes.items || [], tecnicos: tecnicos.items || [], agenda: agenda.items || [] };
}function scheduleItemsForDay(date) { return whatsappScheduleOptions.agenda.filter((item) => item.agendada_para && localDate(item.agendada_para) === date && ["aberta", "em_deslocamento", "em_atendimento"].includes(item.status)); }
function scheduleOptions(tag, items, selected) { return \`<option value="">Não definido</option>\${items.map((item) => \`<option value="\${esc(item.id)}" \${item.id === selected ? "selected" : ""}>\${esc(item.nome)}</option>\`).join("")}\`; }
function scheduleHours(date, equipeId, tecnicoId, currentId, selected) { const busy = scheduleItemsForDay(date).filter((item) => item.id !== currentId && ((equipeId && item.equipe?.id === equipeId) || (tecnicoId && item.tecnico?.id === tecnicoId))).map((item) => new Date(item.agendada_para).getHours()); return Array.from({ length: 12 }, (_, index) => index + 7).map((hour) => \`<option value="\${String(hour).padStart(2, "0")}:00" \${busy.includes(hour) ? "disabled" : ""} \${selected === String(hour).padStart(2, "0") + ":00" ? "selected" : ""}>\${String(hour).padStart(2, "0")}:00\${busy.includes(hour) ? " — ocupado" : ""}</option>\`).join(""); }
function dayAgenda(date) { const items = scheduleItemsForDay(date); return items.length ? \`<span>Agenda: \${items.map((item) => \`\${new Date(item.agendada_para).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })} · \${esc(item.equipe?.nome || item.tecnico?.nome || item.titulo)}\`).join(" | ")}</span>\` : "<span>Agenda livre neste dia.</span>"; }
function whatsappClientForm(conversa) { const dados = conversa.atendimento?.dados || {}; return \`<form data-whatsapp-form="cliente" class="whatsapp-workbench-form"><div class="whatsapp-workbench-title"><span>Pré-cadastro</span><strong>Crie o cliente para montar o orçamento. A O.S. só será aberta após a aprovação.</strong></div><label>Nome<input name="nome" value="\${esc(dados.nome || conversa.nomeContato || "")}" required></label><label>Telefone<input name="telefone" value="\${esc(conversa.telefone || "")}"></label><label>Cidade<input name="cidade" value="\${esc(dados.cidade_bairro || "")}" required></label><label>UF<input name="uf" value="PR" maxlength="2" required></label><label class="whatsapp-field-wide">Endereço<input name="logradouro" placeholder="Rua, avenida ou rodovia"></label><label>Número<input name="numero" placeholder="Nº"></label><label>Bairro<input name="bairro" placeholder="Bairro"></label><label>CPF ou RG<input name="documento" placeholder="CPF ou RG" required></label><label>CEP<input name="cep" placeholder="00000-000"></label><button type="submit">Criar cliente</button></form>\`; }
function money(value) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0)); }
async function loadWhatsappCatalog() { if (whatsappCatalogItems.length) return; const response = await fetch(\`\${apiBaseUrl}/admin/comercial/catalogo\`, { headers: authHeaders() }); if (response.ok) whatsappCatalogItems = (await response.json()).items || []; }
function quoteItemRow() { const options = whatsappCatalogItems.map((item) => \`<option value="\${esc(item.id)}">\${esc(item.grupo)} · \${esc(item.nome)} — \${money(item.valor)}</option>\`).join(""); return \`<div class="whatsapp-quote-line" data-quote-line><select name="catalogo_item" required><option value="">Selecione um item</option>\${options}</select><input name="quantidade" type="number" min="0.001" step="0.001" value="1" required><output>\${money(0)}</output><button type="button" class="secondary-button" data-quote-action="remover" aria-label="Remover item">×</button></div>\`; }
function quoteForm(conversa) { const quote = conversa.orcamentos?.[0]; if (quote) { const items = quote.itens.map((item) => \`<li>\${esc(item.descricao)} <strong>\${money(item.valorTotal)}</strong></li>\`).join(""); return \`<div class="whatsapp-quote-summary"><div><span>Orçamento \${esc(quote.status)}</span><strong>\${esc(quote.titulo)}</strong><ul>\${items}</ul></div><div><b>\${money(quote.total)}</b>\${quote.status === "rascunho" ? \`<button type="button" data-whatsapp-action="enviar-orcamento" data-orcamento-id="\${esc(quote.id)}">Enviar pelo WhatsApp</button>\` : quote.status === "enviado" ? \`<button type="button" data-whatsapp-action="registrar-aceite" data-orcamento-id="\${esc(quote.id)}">Registrar aceite</button>\` : quote.status === "aprovado" ? \`<span>Orçamento aprovado</span>\` : ""}</div></div>\`; } if (!whatsappCatalogItems.length) return \`<div class="whatsapp-quote-summary"><div><span>Orçamento</span><strong>Cadastre itens no catálogo antes de montar a proposta.</strong></div></div>\`; const dados = conversa.atendimento?.dados || {}; return \`<form data-whatsapp-form="orcamento" class="whatsapp-quote-form"><div class="whatsapp-workbench-title"><span>Orçamento</span><strong>Monte a proposta; a O.S. será aberta somente após o aceite.</strong></div><label class="whatsapp-quote-title">Título<input name="titulo" value="Orçamento - \${esc(dados.servico || "atendimento")}" required></label><label>Validade<input name="valido_ate" type="date"></label><div class="whatsapp-quote-lines" data-quote-lines>\${quoteItemRow()}</div><button type="button" class="secondary-button" data-quote-action="adicionar">+ Adicionar item</button><button type="submit">Salvar orçamento</button></form>\`; }
function operationalForm(conversa) { return conversa.cliente ? \`\${quoteForm(conversa)}\${scheduleForm(conversa)}\` : whatsappClientForm(conversa); }
function scheduleForm(conversa) { const os = conversa.ordemServico; const dateValue = whatsappSelectedScheduleDate || (os?.agendadaPara ? localDate(os.agendadaPara) : localDate()); const equipeId = whatsappScheduleDraft.equipeId || os?.equipeId; const tecnicoId = whatsappScheduleDraft.tecnicoId || os?.tecnicoId; const timeValue = os?.agendadaPara ? new Date(os.agendadaPara).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit", hour12: false }) : "07:00"; const previa = conversa.atendimento?.previaOs || {}; const origem = os?.origem || (conversa.orcamentos?.[0]?.status === "aprovado" ? "orcamento_aprovado" : "contrato_recorrencia"); return \`<form data-whatsapp-form="os" class="whatsapp-workbench-form whatsapp-schedule-form"><div class="whatsapp-workbench-title"><span>O.S. \${os ? "criada" : "pendente"}</span><strong>\${esc(os?.titulo || previa.titulo || "Atendimento WhatsApp")}</strong></div><label class="whatsapp-field-wide">Título<input name="titulo" value="\${esc(os?.titulo || previa.titulo || "")}" required></label><label class="whatsapp-field-wide">Detalhes<textarea name="detalhes" rows="1">\${esc(previa.detalhes || "")}</textarea></label><label>Origem<select name="origem"><option value="orcamento_aprovado" \${conversa.orcamentos?.[0]?.status === "aprovado" ? "" : "disabled"} \${origem === "orcamento_aprovado" ? "selected" : ""}>Orçamento aprovado</option><option value="contrato_recorrencia" \${origem === "contrato_recorrencia" ? "selected" : ""}>Contrato ou recorrência</option><option value="servico_gratuito" \${origem === "servico_gratuito" ? "selected" : ""}>Serviço gratuito</option></select></label><label>Data<input name="data" type="date" value="\${dateValue}" required></label><label>Horário<select name="horario" required>\${scheduleHours(dateValue, equipeId, tecnicoId, os?.id, timeValue)}</select></label><label>Equipe<select name="equipe_id">\${scheduleOptions("equipe", whatsappScheduleOptions.equipes, equipeId)}</select></label><label>Técnico<select name="tecnico_id">\${scheduleOptions("tecnico", whatsappScheduleOptions.tecnicos.filter((item) => item.role !== "admin"), tecnicoId)}</select></label><div class="whatsapp-agenda-day">\${dayAgenda(dateValue)}</div><button type="submit">Salvar agendamento</button></form>\`; }

async function loadWhatsappConversation(id) {
  if (id !== selectedWhatsappId) { whatsappSelectedScheduleDate = ""; whatsappScheduleDraft = { equipeId: "", tecnicoId: "" }; }
  const response = await fetch(\`\${apiBaseUrl}/admin/whatsapp/conversas/\${id}\`, { headers: authHeaders() }); if (!response.ok) return;
  const conversa = await response.json(); await Promise.all([loadWhatsappScheduleOptions(), loadWhatsappCatalog()]); selectedWhatsappId = id; selectedWhatsappConversation = conversa; void fetch(\`\${apiBaseUrl}/admin/whatsapp/conversas/\${id}/ler\`, { method: "PATCH", headers: authHeaders() });
  const action = conversa.status === "encerrada" ? '<button class="secondary-button" data-whatsapp-action="reabrir">Reabrir conversa</button>' : conversa.atribuidoUsuario ? '<button class="secondary-button" data-whatsapp-action="liberar">Liberar para fila</button><button class="danger-button" data-whatsapp-action="encerrar">Encerrar</button>' : '<button class="danger-button" data-whatsapp-action="encerrar">Encerrar</button>';
  const form = operationalForm(conversa);
  document.querySelector("#whatsappConversationDetail").innerHTML = \`<header class="whatsapp-detail-header"><div class="whatsapp-detail-person"><span class="whatsapp-avatar whatsapp-avatar-large">\${esc((conversa.nomeContato || conversa.telefone || "?").slice(0, 1).toUpperCase())}</span><div><h3>\${esc(conversa.nomeContato || conversa.telefone)}</h3><p>\${esc(conversa.telefone || "Sem telefone")} · \${conversa.status === "encerrada" ? "Conversa encerrada" : conversa.atribuidoUsuario ? \`Atendimento com \${esc(conversa.atribuidoUsuario.nome)}\` : "Aguardando atendente"}</p></div></div><div class="whatsapp-detail-actions">\${action}<button class="danger-button" data-whatsapp-action="apagar">Apagar conversa</button></div></header><div class="whatsapp-operational-strip">\${form}</div><div class="whatsapp-detail-body"><div class="whatsapp-thread-wrap"><div class="whatsapp-thread-heading"><strong>Histórico da conversa</strong><span>\${conversa.mensagens.length} mensagens</span></div><div class="whatsapp-thread">\${conversa.mensagens.map((item) => \`<div class="whatsapp-message whatsapp-message-\${item.direcao}"><small>\${item.direcao === "entrada" ? "Cliente" : "AIRMOVEBR"} · \${esc(formatDate(item.criadoEm))}</small><p>\${esc(item.texto)}</p></div>\`).join("")}</div><form class="whatsapp-reply-form" id="whatsappReplyForm"><textarea name="texto" rows="2" placeholder="Escreva uma resposta..." required></textarea><div><span>A primeira resposta assume a conversa automaticamente.</span><button type="submit">Enviar resposta</button></div></form></div></div>\`;
  renderWhatsappConversations(); requestAnimationFrame(() => { const thread = document.querySelector(".whatsapp-thread"); if (thread) thread.scrollTo({ top: thread.scrollHeight, behavior: "smooth" }); });
}

async function connectWhatsappEvents() { whatsappEventAbort?.abort(); whatsappEventAbort = new AbortController(); try { const response = await fetch(\`\${apiBaseUrl}/admin/whatsapp/eventos\`, { headers: { ...authHeaders(), Accept: "text/event-stream" }, signal: whatsappEventAbort.signal }); if (!response.ok || !response.body) return; const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const part = await reader.read(); if (part.done) break; buffer += decoder.decode(part.value, { stream: true }); const blocks = buffer.split("\\n\\n"); buffer = blocks.pop() || ""; for (const block of blocks) { const line = block.split("\\n").find((item) => item.startsWith("data:")); if (!line) continue; const event = JSON.parse(line.slice(5)); if (event.tipo === "transferida_humano" && lastWhatsappEvent !== event.conversaId) { lastWhatsappEvent = event.conversaId; if (window.Notification?.permission === "granted") new Notification("WhatsApp aguardando atendente"); } void loadWhatsappConversations(); if (selectedWhatsappId === event.conversaId) void loadWhatsappConversation(selectedWhatsappId); } } } catch { /* A atualização de um minuto continua ativa. */ } }
async function preencherEnderecoWhatsappPorCep(input) {
  const cep = String(input.value || "").replace(/\\D/g, "");
  if (cep.length !== 8 || input.dataset.cepConsultado === cep) return;
  input.dataset.cepConsultado = cep;
  try {
    const response = await fetch(\`https://viacep.com.br/ws/\${cep}/json/\`);
    const endereco = await response.json();
    if (!response.ok || endereco.erro) return;
    const form = input.closest("form");
    const preencher = (nome, valor) => { const campo = form?.elements.namedItem(nome); if (campo && valor) campo.value = valor; };
    preencher("logradouro", endereco.logradouro);
    preencher("bairro", endereco.bairro);
    preencher("cidade", endereco.localidade);
    preencher("uf", endereco.uf);
  } catch { input.dataset.cepConsultado = ""; }
}
async function whatsappAction(action) { if (action === "apagar" && !window.confirm("Apagar esta conversa e todo o histórico? A próxima mensagem deste número iniciará um novo atendimento.")) return; const path = action === "liberar" ? "liberar" : action === "reabrir" ? "reabrir" : action === "encerrar" ? "encerrar" : ""; const method = action === "apagar" ? "DELETE" : action === "encerrar" || action === "reabrir" ? "POST" : "PATCH"; const response = await fetch(apiBaseUrl + "/admin/whatsapp/conversas/" + selectedWhatsappId + (path ? "/" + path : ""), { method, headers: { ...authHeaders(), "Content-Type": "application/json" }, body: action === "encerrar" ? JSON.stringify({ motivo: "concluido" }) : undefined }); if (!response.ok) { window.alert("Não foi possível concluir esta ação."); return; } if (action === "apagar") { selectedWhatsappId = ""; document.querySelector("#whatsappConversationDetail").innerHTML = '<div class="whatsapp-empty-state"><span class="whatsapp-empty-icon">◉</span><strong>Conversa apagada</strong><p>Envie uma nova mensagem pelo WhatsApp para iniciar o atendimento novamente.</p></div>'; await loadWhatsappConversations(); return; } await loadWhatsappConversation(selectedWhatsappId); await loadWhatsappConversations(); }

whatsappNav.addEventListener("click", (event) => { event.stopImmediatePropagation(); showWhatsappView(); });
document.querySelectorAll(".nav-link").forEach((link) => link.addEventListener("click", () => { if (link !== whatsappNav) hideWhatsappView(); }));
document.querySelector("#whatsappRefreshButton").addEventListener("click", () => void loadWhatsappConversations());
document.querySelector("#whatsappSearchInput").addEventListener("input", renderWhatsappConversations);
document.querySelector(".whatsapp-filters").addEventListener("click", (event) => { const target = event.target.closest("[data-whatsapp-filter]"); if (!target) return; document.querySelectorAll("[data-whatsapp-filter]").forEach((item) => item.classList.toggle("is-active", item === target)); renderWhatsappConversations(); });
document.querySelector("#whatsappConversationList").addEventListener("click", (event) => { const target = event.target.closest("[data-whatsapp-id]"); if (target) void loadWhatsappConversation(target.dataset.whatsappId); });
document.querySelector("#whatsappConversationDetail").addEventListener("click", async (event) => { const action = event.target.dataset.whatsappAction; if (action === "registrar-aceite") { if (!window.confirm("Confirma que o cliente aprovou este orçamento pelo WhatsApp?")) return; const response = await fetch(\`\${apiBaseUrl}/admin/comercial/orcamentos/\${event.target.dataset.orcamentoId}/aceite-whatsapp\`, { method: "POST", headers: authHeaders() }); if (!response.ok) { window.alert("Não foi possível registrar o aceite."); return; } await loadWhatsappConversation(selectedWhatsappId); return; } if (action === "enviar-orcamento") { const response = await fetch(\`\${apiBaseUrl}/admin/comercial/orcamentos/\${event.target.dataset.orcamentoId}/enviar\`, { method: "POST", headers: authHeaders() }); if (!response.ok) { window.alert("Não foi possível enviar o orçamento."); return; } await loadWhatsappConversation(selectedWhatsappId); return; } if (action) await whatsappAction(action); });
document.querySelector("#whatsappConversationDetail").addEventListener("input", (event) => { if (event.target.name === "cep" && event.target.closest('[data-whatsapp-form="cliente"]')) void preencherEnderecoWhatsappPorCep(event.target); });
document.querySelector("#whatsappConversationDetail").addEventListener("change", (event) => { if (["data", "equipe_id", "tecnico_id"].includes(event.target.name)) { if (event.target.name === "data") whatsappSelectedScheduleDate = event.target.value; if (event.target.name === "equipe_id") whatsappScheduleDraft.equipeId = event.target.value; if (event.target.name === "tecnico_id") whatsappScheduleDraft.tecnicoId = event.target.value; void loadWhatsappConversation(selectedWhatsappId); } });
document.querySelector("#whatsappConversationDetail").addEventListener("click", (event) => {
  const target = event.target.closest("[data-quote-action]"); if (!target) return;
  const form = target.closest("form"); const lines = form?.querySelector("[data-quote-lines]");
  if (target.dataset.quoteAction === "adicionar" && lines) lines.insertAdjacentHTML("beforeend", quoteItemRow());
  if (target.dataset.quoteAction === "remover" && form?.querySelectorAll("[data-quote-line]").length > 1) target.closest("[data-quote-line]")?.remove();
});
document.querySelector("#whatsappConversationDetail").addEventListener("change", (event) => {
  if (event.target.name !== "catalogo_item") return; const line = event.target.closest("[data-quote-line]"); const item = whatsappCatalogItems.find((entry) => entry.id === event.target.value); if (line && item) line.querySelector("output").textContent = money(item.valor * Number(line.querySelector('[name="quantidade"]').value || 0));
});
document.querySelector("#whatsappConversationDetail").addEventListener("input", (event) => {
  if (event.target.name !== "quantidade") return; const line = event.target.closest("[data-quote-line]"); const item = whatsappCatalogItems.find((entry) => entry.id === line?.querySelector('[name="catalogo_item"]')?.value); if (line && item) line.querySelector("output").textContent = money(item.valor * Number(event.target.value || 0));
});document.querySelector("#whatsappConversationDetail").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.target; const data = new FormData(form); let response; if (form.id === "whatsappReplyForm") { const texto = String(data.get("texto") || "").trim(); if (!texto) return; response = await fetch(\`\${apiBaseUrl}/admin/whatsapp/conversas/\${selectedWhatsappId}/mensagens\`, { method: "POST", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ texto }) }); } else if (form.dataset.whatsappForm === "cliente") { response = await fetch(\`\${apiBaseUrl}/admin/whatsapp/conversas/\${selectedWhatsappId}/cliente\`, { method: "POST", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ tipo: "pf", nome: data.get("nome"), documento: data.get("documento"), telefone: data.get("telefone"), cep: data.get("cep"), logradouro: data.get("logradouro"), numero: data.get("numero"), bairro: data.get("bairro"), cidade: data.get("cidade"), uf: String(data.get("uf") || "").toUpperCase() }) }); } else if (form.dataset.whatsappForm === "orcamento") { const itens = Array.from(form.querySelectorAll("[data-quote-line]")).map((line) => { const item = whatsappCatalogItems.find((entry) => entry.id === line.querySelector('[name="catalogo_item"]').value); return item && { item_catalogo_id: item.id, tipo: item.tipo, descricao: item.nome, unidade: item.unidade, quantidade: Number(line.querySelector('[name="quantidade"]').value), valor_unitario: Number(item.valor) }; }).filter(Boolean); response = await fetch(\`\${apiBaseUrl}/admin/comercial/orcamentos\`, { method: "POST", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ cliente_id: selectedWhatsappConversation?.cliente?.id || "", conversa_id: selectedWhatsappId, titulo: data.get("titulo"), valido_ate: data.get("valido_ate") || undefined, itens }) }); } else if (form.dataset.whatsappForm === "os") { const equipeId = String(data.get("equipe_id") || ""); const tecnicoId = String(data.get("tecnico_id") || ""); if (!equipeId && !tecnicoId) { window.alert("Selecione uma equipe ou um técnico antes de agendar."); return; } response = await fetch(\`\${apiBaseUrl}/admin/whatsapp/conversas/\${selectedWhatsappId}/os\`, { method: "POST", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ titulo: data.get("titulo"), detalhes: data.get("detalhes"), origem: data.get("origem"), equipe_id: equipeId || undefined, tecnico_id: tecnicoId || undefined, agendada_para: \`\${data.get("data")}T\${data.get("horario")}:00\` }) }); }
  if (!response?.ok) { const erro = await response?.json().catch(() => null); window.alert(erro?.message || "Não foi possível salvar o atendimento."); return; } whatsappScheduleOptions.agenda = []; await loadWhatsappScheduleOptions(); await loadWhatsappConversation(selectedWhatsappId); await loadWhatsappConversations(); });
`;